trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '0176f1d2-6521-4fcb-8ea0-d656f0bee373/757afba2-1461-4bba-b690-c4e73f14e99b'
    vstsFeedPackagePublish: 'terraform-modules'
    versionOption: 'patch'
    packagePublishDescription: 'terraform-modules'
