trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '6a528f3d-6964-4b48-8982-2b996a53962a/fbd4e452-6a63-4cdb-bc6f-418c1d0a9719'
    versionOption: 'patch'
    packagePublishDescription: 'terraform-modules'
